name: Drumsheds

on:
  push:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

concurrency:
  group: drumsheds

jobs:
  check_tickets_repeatedly:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4
      - name: Set script permissions
        run: chmod +x script.sh
      - name: Check tickets
        run: |
            for run in {1..20}; do
              sleep 1m
              sh script.sh
            done
