name: Drumsheds

on:
  push:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  check_tickets:
    runs-on: ubuntu-latest
    steps:
      - name: Get tickets
        run: ./script.sh
