name: Almeida

on:
  push:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  check_tickets:
    runs-on: ubuntu-latest
    steps:
      - name: Get tickets
        run: |
          RESPONSE=$(curl -s 'https://bookings.drumshedslondon.com/api/4.0/package/ticketavailability' -H 'cookie: kabFLOW=%2CsqAXsw6eoJK1KBKpT2Jrau4Eut3bNF7eoYdywsVSGpjYOSNYIxXxdRcwbhFUmzy' -H 'package-id: 20092')
          
          echo $RESPONSE

          CALCULATED_HASH=$(echo -n $RESPONSE | sha256sum)

          echo $CALCULATED_HASH

          if [ "$CALCULATED_HASH" = "abc" ]; then
            echo "The strings are equal."
          else
            echo "The strings are not equal."
            exit 111
          fi
