name: Drumsheds

on:
  push:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

concurrency:
  group: drumsheds-workflow

jobs:
  check_tickets_repeatedly:
    runs-on: ubuntu-latest
    concurrency:
      group: drumsheds-job
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4
      - name: sleep
        run: sleep 1m
      - name: Set script permissions
        run: chmod +x script.sh
      - name: Check tickets
        run: |
            for run in {1..20}; do
              sh script.sh
            done
