name: Drumsheds

on:
  push:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

concurrency:
  group: drumsheds

jobs:
  check_tickets:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - name: Set script permissions
        run: chmod +x script.sh
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'npm'
      - run: npm ci
      - name: Check tickets
        id: check-tickets-step
        run: |
            for run in {1..120}; do
              sh script.sh
              exit_code=$(cat output.txt)
              echo $exit_code
              if [ $exit_code -eq 111 ]; then
                echo "exit_code $exit_code is 111, exiting with 0"
                exit 0
              elif [ $exit_code -ne 0 ]; then
                echo "exit_code is not 111, exiting with $exit_code"
                exit $exit_code
              fi
              sleep 10
            done
      - name: Add to basket
        run: node playwright-script.js
        if: steps.check-tickets-step.outputs.tickets == 'true'
