name: Drumsheds

on:
  push:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

concurrency:
  group: drumsheds

jobs:
  check_tickets:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - name: Set script permissions
        run: chmod +x script.sh
      - name: Check tickets
        run: |
            for run in {1..20}; do
              sh script.sh
              sleep 1m
            done
